# Generated by Django 3.2.13 on 2022-05-24 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_account_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='display_name',
            field=models.CharField(default='hogehoge', max_length=100),
        ),
    ]
