# Generated by Django 3.2.13 on 2022-05-19 14:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('span', models.IntegerField(default=4)),
                ('start_date', models.DateTimeField()),
                ('published_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('span', models.IntegerField(default=12)),
                ('start_date', models.DateTimeField()),
                ('published_date', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('span', models.IntegerField(default=7)),
                ('start_date', models.DateTimeField()),
                ('published_date', models.DateTimeField(auto_now=True)),
                ('month_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timeline.month')),
            ],
        ),
        migrations.AddField(
            model_name='month',
            name='year_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timeline.year'),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('detail', models.TextField()),
                ('date', models.DateTimeField(default=datetime.datetime(2022, 5, 19, 14, 15, 45, 647121, tzinfo=utc))),
                ('published_date', models.DateTimeField(auto_now=True)),
                ('week_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timeline.week')),
            ],
        ),
    ]
