# Generated by Django 3.2.13 on 2022-05-22 06:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 22, 6, 27, 40, 56715, tzinfo=utc)),
        ),
    ]
