# Generated by Django 3.2.13 on 2022-06-05 07:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0006_alter_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 5, 7, 50, 6, 505653, tzinfo=utc), help_text='日付'),
        ),
        migrations.AlterField(
            model_name='event',
            name='detail',
            field=models.TextField(help_text='詳細'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(help_text='名前', max_length=200),
        ),
    ]
