# Generated by Django 3.2.13 on 2022-06-06 02:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0007_auto_20220605_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='week_id',
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 6, 2, 11, 53, 535312, tzinfo=utc), help_text='日付'),
        ),
    ]
