# Generated by Django 3.2.13 on 2022-06-06 02:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0011_auto_20220606_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 6, 2, 35, 41, 876322, tzinfo=utc), help_text='日付'),
        ),
        migrations.AlterField(
            model_name='month',
            name='start_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='week',
            name='start_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='year',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
